FROM mysql:5

# logs should go to stdout / stderr
# RUN	ln -sfT /dev/stderr /var/log/mysql/error.log; \
# 	ln -sfT /dev/stdout /var/log/mysql/query.log; \
# 	# ln -sfT /dev/stdout "$APACHE_LOG_DIR/other_vhosts_access.log"; \
# 	chown -R --no-dereference mysql:mysql /var/log/mysql